const ADD_SERVICE = 'ADD_SERVICE';
const REMOVE_SERVICE = 'REMOVE_SERVICE';
const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
const ADD_CHANGES_SERVICE = 'ADD_CHANGES_SERVICE';
const EDIT_SERVICE = 'EDIT_SERVICE';
const END_SERVICE_EDITING = 'END_SERVICE_EDITING'
export {ADD_SERVICE,REMOVE_SERVICE,CHANGE_SERVICE_FIELD,ADD_CHANGES_SERVICE, EDIT_SERVICE, END_SERVICE_EDITING};
